### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Pantalaymon** [LoicGrobol/decofre#6] opened 2021-02-11 18:27 UTC
As mentioned in my mail I have tried to use decofre but I face an import error as soon as I try to run the pretrained model.

So after installing with `python3 -m pip install --pre decofre` on Ubuntu Terminal (Windows Machine) and installing the spacy dependencies I downloaded ANCOR and ran the bootsctrap script.

Then I run `decofre-train --config tests/sanity-check.jsonnet --model-config decofre/models/default.jsonnet --out-dir /modelecoref`.

I'm getting this exception : 
![image](https://user-images.githubusercontent.com/60576980/107680860-aee7ee00-6c9e-11eb-94f7-4d73edd32d73.png)

It seems that there is no "ignite" file in the decofre folder? how do I fix this?

**Comment by LoicGrobol** [comment] 2021-02-12 15:25
What is the output of  `python3.8 -m pip show pip pytorch-ignite`?

**Comment by Pantalaymon** [comment] 2021-02-12 15:52
> What is the output of `python3.8 -m pip show pip pytorch-ignite`?

I get this : 
![image](https://user-images.githubusercontent.com/60576980/107789977-8c171180-6d52-11eb-80d6-6a5a84f67c80.png)

**Comment by LoicGrobol** [comment] 2021-02-12 19:15
OK, I think I know what the problem is. I have pushed a new version to Pypi that pins ignite to the 0.4 branch. Please try installing again and tell me if it works now.

**Comment by Pantalaymon** [comment] 2021-02-15 13:11
> OK, I think I know what the problem is. I have pushed a new version to Pypi that pins ignite to the 0.4 branch. Please try installing again and tell me if it works now.

Thanks. reinstalled decofre.

the issue seems to have been fixed but now I run into this : 
![image](https://user-images.githubusercontent.com/60576980/107952067-8fe8a500-6f99-11eb-8b5a-9385035f7c0f.png)

Edit: I have over 250 GB left on my HDD .

**Comment by LoicGrobol** [comment] 2021-02-16 09:25
OK, that's a different issue, and I might know why this happens (the default size reserved for the dataset is huge, no matter what the actual size is) but could you fill a different issue for it?

**Comment by LoicGrobol** [comment] 2021-02-16 09:25
closed by 9ad3fd316c

**Closed as completed by LoicGrobol** 2021-02-16 09:25 UTC
Labels: needinfo
